#!/bin/python3

#  SPDX-License-Identifier: BSD-3-Clause
#
#  simple pakcet generator. Packet are generated by random walk.
#
#  Copyright (C) 2022 CESNET
#  Author(s):
#    Radek Iša <isa@cesnet.cz>


from parser import *
import scapy.utils
import string
import argparse
import time

def main():
    #parse options
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file_output", type=str,
                        help="Set output file", required=True)
    parser.add_argument("-p", "--packets", type=int,
                        help="number of generated packets", default=20)
    parser.add_argument("-s", "--seed", type=int,
                        help="set seed to random generator", default=time.time())
    args = parser.parse_args()

    gen = ethernet()
    packets = []
    random.seed(args.seed)
    for x in range(args.packets):
        cfg = packet_config()
        protocols = []
        gen.packet_gen(protocols, cfg)
        packet = scapy.packet.Packet()
        for pr in protocols:
            packet = packet/pr

        packets.append(scapy.packet.fuzz(packet))

    scapy.utils.wrpcap(args.file_output, packets)


if __name__ == "__main__":
    main()
